### ISSUE TITLE
HASS Add-on broken on HASSOS 9.0

### ISSUE THREAD

**Issue by sephiroth1395** [jens-maus/RaspberryMatic#1942]
### Describe the issue you are experiencing

Since the upgrade to HASSOS 9.0, the add-on cannot start.  I suspect this is due to the docker migration to cgroups2.

Error message from the Supervisor:

```
22-09-15 13:34:43 ERROR (MainThread) [supervisor.docker.addon] Can't set cgroup permission on the host for addon_de838cd8_raspberrymatic
22-09-15 13:34:43 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-14879' coro=<DockerAddon._hardware_events() done, defined at /usr/src/supervisor/supervisor/jobs/decorator.py:85> exception=DockerError("Can't set cgroup permission on the host for addon_de838cd8_raspberrymatic")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 720, in _hardware_events
    await self.sys_dbus.agent.cgroup.add_devices_allowed(
  File "/usr/src/supervisor/supervisor/dbus/agent/cgroup.py", line 19, in add_devices_allowed
    await self.dbus.CGroup.AddDevicesAllowed(container_id, permission)
  File "/usr/src/supervisor/supervisor/utils/dbus.py", line 174, in call_dbus
    raise DBusFatalError(reply.body[0])
supervisor.exceptions.DBusFatalError: Error calling runc for '87542225ef424bd38c4d49ff3db5a8c46b277fdee1c3efd1a6aee5edd57d9d80': exit status 1, output time="2022-09-15T11:34:43Z" level=warning msg="could not find device group for '99/204' in /proc/devices -- temporarily ignoring rule: {99 204 -1 rwm true}"
time="2022-09-15T11:34:43Z" level=info msg="found more than one filter (2) attached to a cgroup -- removing extra filters!"
time="2022-09-15T11:34:43Z" level=info msg="removing old filter 0 from cgroup" id=139 name= run_count=0 runtime=0s tag=f231b56d360e591c type=CGroupDevice
time="2022-09-15T11:34:43Z" level=info msg="removing old filter 1 from cgroup" id=140 name= run_count=0 runtime=0s tag=be0b8d7ca6afd4d8 type=CGroupDevice
time="2022-09-15T11:34:43Z" level=warning msg="could not find device group for '99/204' in /proc/devices -- temporarily ignoring rule: {99 204 -1 rwm true}"
time="2022-09-15T11:34:43Z" level=info msg="found more than one filter (2) attached to a cgroup -- removing extra filters!"
time="2022-09-15T11:34:43Z" level=info msg="removing old filter 0 from cgroup" id=144 name= run_count=0 runtime=0s tag=839fa1b30f0f67c3 type=CGroupDevice
time="2022-09-15T11:34:43Z" level=info msg="removing old filter 1 from cgroup" id=147 name= run_count=0 runtime=0s tag=be0b8d7ca6afd4d8 type=CGroupDevice
time="2022-09-15T11:34:43Z" level=error msg="failed to call BPF_PROG_DETACH (BPF_CGROUP_DEVICE) on old filter program: can't detach program: no such file or directory"
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 141, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 139, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 727, in _hardware_events
    raise DockerError(
supervisor.exceptions.DockerError: Can't set cgroup permission on the host for addon_de838cd8_raspberrymatic
22-09-15 13:34:43 ERROR (MainThread) [supervisor.docker.addon] Can't set cgroup permission on the host for addon_de838cd8_raspberrymatic
```

### Describe the behavior you expected

The add-on successfully starts.

### Steps to reproduce the issue

1. Upgrade to HASSOS 9.0
2. Try to start the add-on

### What is the version this bug report is based on?

3.65.8.20220831

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
No.
```

### Additional information

I'm using the ELV USB stick.

**Comment by sephiroth1395** [comment]
One thing I forgot to add: the situation prevents `rfd` from starting.

**Comment by H3xF2x** [comment]
I hit accidential the upgrade button - never install a x.0 version on a productive system :-(

Here the update prevents the hmip from starting:
```
Setting LAN Gateway keys: OK
Starting hs485d: OK
Starting multimacd: .OK
Starting rfd: .OK
Starting HMIPServer: .......................................................................................................................................................ERROR
Starting ReGaHss: .OK
```

**Comment by ozwo71** [comment]
...same for me but with RPI-RF-MOD:

`Starting multimacd: .OK
Starting rfd: ....................ERROR
Starting HMIPServer: ..............OK`

**Comment by jens-maus** [comment]
Obviously (as the error messages states) the cgroup settings/permissions cannot be setup correctly with HomeAssistantOS 9.0 at the moment. Thus, anyone using the RaspberryMatic CCU" Add-on in production should stay with "HomeAssistantOS v8 for the time being.

**Comment by agners** [comment]
Hm, this seems to be the relevant error:

```
supervisor.exceptions.DBusFatalError: Error calling runc for '87542225ef424bd38c4d49ff3db5a8c46b277fdee1c3efd1a6aee5edd57d9d80': exit status 1, output time="2022-09-15T11:34:43Z" level=warning msg="could not find device group for '99/204' in /proc/devices -- temporarily ignoring rule: {99 204 -1 rwm true}"
```

This is definitely caused by the move to CGroupsV2 (https://github.com/home-assistant/operating-system/pull/1329).

It seems that device permissions set via runc has a problem with that particular device: `could not find device group for '99/204' in /proc/devices -- temporarily ignoring rule: {99 204 -1 rwm true}`

> I'm using the ELV USB stick.

Is that the HM-CFG-USB-2? I do have such a stick somewhere, but can't find it right now :cry: 

> I hit accidential the upgrade button - never install a x.0 version on a productive system :-(

Ideally, run a staging system and install beta/rc's there... Then .0 are painless :wink:

**Comment by ozwo71** [comment]
> And please note, it seems that even users with a RPI-RF-MOD seem to have issues since 9.0

I can confirm this. After the downgrade to 8.5 everything is fine again.

**Comment by agners** [comment]
> And please note, it seems that even users with a RPI-RF-MOD seem to have issues since 9.0

Hm, are those using UART I guess? So enabling access to UART fails in this case?

I am not 100% sure what I need, I need to understand why my test case (deCONZ and a couple of USB sticks) works while this one does not. It seems that `runc` rejects that device on this line: https://github.com/opencontainers/runc/blob/v1.1.4/libcontainer/cgroups/systemd/common.go#L279

**Comment by H3xF2x** [comment]
> And please note, it seems that even users with a RPI-RF-MOD seem to have issues since 9.0
Well, I'm using a `HM-MOD-RPI-PCB`, seems every radio is affected.

> Ideally, run a staging system and install beta/rc's there... Then .0 are painless

Oh yes - it wasn't my intention to debug on the production system ...

**Comment by jens-maus** [comment]
> > And please note, it seems that even users with a RPI-RF-MOD seem to have issues since 9.0
> 
> Well, I'm using a `HM-MOD-RPI-PCB`, seems every radio is affected.

How do you guys have your `HM-MOD-RPI-PCB` or `RPI-RF-MOD` connected? Via GPIO or via a `HB-RF-USB` adapter?

**Comment by jens-maus** [comment]
> > And please note, it seems that even users with a RPI-RF-MOD seem to have issues since 9.0
> 
> Hm, are those using UART I guess? So enabling access to UART fails in this case?
> 
> I am not 100% sure what I need, I need to understand why my test case (deCONZ and a couple of USB sticks) works while this one does not. It seems that `runc` rejects that device on this line: https://github.com/opencontainers/runc/blob/v1.1.4/libcontainer/cgroups/systemd/common.go#L279

Well, this could easily be two independent issues here. One with using a USB connected RF Module like `HmIP-RFUSB` or `HM-CFG-USB-2` like the author of this issue ticket here. And the other one, e.g. the `eq3_char_loop` kernel module not being able to dynamically generate the `/dev/mmd_bidcos` `/dev/mmd_hmip` device node pairs upon startup due to other more restrictive permissions in cgroupsv2.

**Comment by ozwo71** [comment]
I'm using the RPI-RF-MOD via GPIO

**Comment by jens-maus** [comment]
> Via GPIO (CM4 via mainboard)

Do you see any similar permission or cgroupv2 related issues in the HomeAssistant logfiles? Because you only showed logs of the RaspberryMatic Addon startup, but not showing if HomeAssistantOS was logging some issues as well.

**Comment by H3xF2x** [comment]
`Do you see any similar permission or cgroupv2 ...`

Seems the logs are gone afert downgrade and restore, sorry.

**Comment by ozwo71** [comment]
...I will do the upgrade again...

**Comment by ozwo71** [comment]
home-assistant.log only shows:

`home-assistant.log.1:2022-09-15 17:31:12.344 WARNING (MainThread) [hahomematic.central_unit] create_clients failed: Unable to create client for central [('Unable to authenticate (<ProtocolError for de838cd8-raspberrymatic:2001/RPC2: 401 Unauthorized>,).',)]. Check logs.

home-assistant.log.1:2022-09-15 17:31:13.581 WARNING (MainThread) [hahomematic.central_unit] create_clients failed: Unable to create client for central [('Unable to authenticate (<ProtocolError for de838cd8-raspberrymatic:2010/RPC2: 401 Unauthorized>,).',)]. 

home-assistant.log.1:2022-09-15 17:31:43.627 WARNING (MainThread) [hahomematic.central_unit] check_connection failed: No clients exist. Trying to create clients for server RaspberryMatic
`
Is there any special debug setting or another log that will help?

**Comment by ozwo71** [comment]
...Interesting: I had the problem after upgrading to 9.0 and found this issue when neither restarting the add-on nor rebooting the raspbi helped.

Then downgraded again to 8.5 using
`ha os update --version 8.5`

To reproduce the error I just did
`ha os update`

Again I am on 9.0 and guess what: RaspberryMatic is running after rebooting...

**Comment by pvizeli** [comment]
Does a restart of the add-on fix the issue? (Just for debugging)

**Comment by agners** [comment]
@sephiroth1395 do you happen to have access to the OS shell? If so, can you get the logs of `journalctl -u haos-agent.service` and a capture of `/proc/devices` when the device is plugged in?

**Comment by pvizeli** [comment]
> > Via GPIO (CM4 via mainboard)
> 
> Do you see any similar permission or cgroupv2 related issues in the HomeAssistant logfiles? Because you only showed logs of the RaspberryMatic Addon startup, but not showing if HomeAssistantOS was logging some issues as well.

<img width="1517" alt="image" src="https://user-images.githubusercontent.com/15338540/190481915-e3726170-16cb-450a-8d2d-6d9493794323.png">

The issue is that the driver seems not to work correctly and gets somehow closed after it gets created. I guess they have to be fixed in a upcoming release

**Comment by andreas-bulling** [comment]
same problem here. Downgrade to OS 8.5 helped

**Comment by pvizeli** [comment]
@jens-maus 
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/15338540/190483980-8a7a0852-035c-4bf8-a23c-b4860658e2f1.png">

**Comment by Nielsvo** [comment]
I am using the HmIP-RFUSB USB stick on my Synology NAS (OVA). Had the same issue when upgrading to 9.0 and downgraded to 8.5 and then it worked again. But I can't seem to upgrade again to 9.0 now? No update available?

**Comment by pvizeli** [comment]
We take it down but it comes soon back. We was not sure if that is an bug with cgroup or and homematic custom kernel driver bug with the kernel version.

**Comment by jens-maus** [comment]
BTW: Here is the source code for the `eq3_char_loop` kernel driver: https://github.com/eq-3/occu/blob/master/KernelDrivers/eq3_char_loop.c

Note that it uses `ioctl()` for certain purposes and in the past we already had some issues with it working correctly (similar to the issues shown here) but they were all permission related, e.g. the closed docker environment not allowing to access these dynamically generated device nodes..... Thus, this must be related to the cgroupsv2 switch...

**Comment by pvizeli** [comment]
https://github.com/home-assistant/supervisor/pull/3868 that should at least fix the error which we get on the supervisor logs but it not affect the permissions at all. Also, the kernel driver creates the devices which are not affected by the container cgroup permissions.

**Comment by sotatech** [comment]
I saw that HAOS 9.0 had been pulled yesterday, so when it reappeared, I foolishly assumed it was fixed.  No so, I et the following error on starup of the add-in:

`Starting rfd: ....................ERROR
Starting HMIPServer: ........OK
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting Third-Party Addons: OK
find: /usr/local/etc/monit*.cfg: No such file or directory
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.65.8.20220831 (raspmatic_oci_amd64)`

I'm using an HB-RF-ETH in case it's relevant.

**Comment by jens-maus** [comment]
Indeed the HA authors seem to have decided to bring it back, thought the issue hasn't been resolved and IMHO is still located in the cgroupsv2 upgrade in HAOS9. IMHO it would have been better to wait a few more days trying to fox+reproduce it because I still feel this isn't an issue in the RaspberryMatic Addon itself but rather an introduced incompatibility/regression in HAOS9

**Comment by sotatech** [comment]
Thanks, It's not heating season here yet, so it's not urgent for me. I'll wait and see what happens before rolling back if necessary.

**Comment by pvizeli** [comment]
> Indeed the HA authors seem to have decided to bring it back, thought the issue hasn't been resolved and IMHO is still located in the cgroupsv2 upgrade in HAOS9. IMHO it would have been better to wait a few more days trying to fox+reproduce it because I still feel this isn't an issue in the RaspberryMatic Addon itself but rather an introduced incompatibility/regression in HAOS9

I tested the os-agent, and the permission got to apply to the container. However, we see a kernel module that does not run at the container namespace, and that decides to remove the devices after it is created it. Custom kernel modules are just best effort and will never interrupt a release. We rollback to 8.5 because I was not sure if that is an issue with runc, but after several tests and debugs, that part works fine. The container gets access to such devices, however, the kernel module creates such knodes on /dev and manages that not the container itself. They only access the devices after it got created. If the person who have created the issue would have posted the full supervisor logs and also the kernel logs, that would show nice what is going on. So I agree that the kernel driver from eq3 have compatibility issues at the kernel and I have no idea why. However, we had a beta phase to test it and fix it.

**Comment by JoMass** [comment]
Since I have this problem, I searched hard how to go back to version 8.5, but could not find a suitable method.  
Could someone give me a tip on how to reset HA OS to the previous version,   please,   thanks

**Comment by H3xF2x** [comment]
@JoMass 
Enable ssh on Hassos 
FYI: ssh to port 22222 and execute
`# ha os update --version 8.5`

**Comment by JoMass** [comment]
Great, worked perfectly;  Thank you @H3xF2x

**Comment by jens-maus** [comment]
Please note that with the next nightly snapshot this issues should be hopefully solved/fixed by having introduced an additional `sleep 5` call after `multimacd` startup. Also note that a newer HomeAssistant supervisor version (2022.09.dev1703 or newer) seem to be required as well.

**Comment by opu1000** [comment]
Hello all, hello Jens, is there a date planned to publish the new version with the fix?
Regards OPU

**Comment by jens-maus** [comment]
RTF-Milestone: https://github.com/jens-maus/RaspberryMatic/milestones

**Comment by JoMass** [comment]
I'm sorry to report, the latest release  still does not works with HS-OS9.0
Downgrade to 8.5 and rasperrymatic  runs at it should



Logfile
Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: onboard, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.2, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.1.auto-1.1, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-xhci-hcd.1.auto-1.1, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting sshd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ..............ERROR
Starting rfd: ERROR: /dev/mmd_bidcos missing, no BidCos-RF hardware found
Starting HMIPServer: ERROR: /dev/mmd_hmip missing
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.65.11.20221005 (raspmatic_oci_arm64)

**Comment by jens-maus** [comment]
> I'm sorry to report, the latest release still does not works with HS-OS9.0

Whats the bade hardware on which you have installed HomeAssistantOS?

**Comment by JoMass** [comment]
Odroid N2+ 4GB 64GB-SSD

**Comment by jens-maus** [comment]
> Odroid N2+ 4GB 64GB-SSD

Dachte ich mir schon. Dann geht es hier weiter für dich: https://github.com/jens-maus/RaspberryMatic/issues/1969

**Comment by andreas-bulling** [comment]
Does it work with HomeAssistant OS v9.2?

**Comment by ChristophCaina** [comment]
@andreas-bulling yes, for me it was working, even I have the information still in my notifications after the reboot.
But the Addon itself is starting as expected.
![grafik](https://user-images.githubusercontent.com/26391061/195194804-3e778d98-ee9d-4b1f-8cb4-42f6d4b62d59.png)

I guess, with the new release of the Addon (recently) there is a delay in the startup sequence, and this is causing the log message.

**Comment by FlapFlup** [comment]
Hello, in my system (Odroid with HmIP-RFUSB) the error no longer occurs under HomeAssistant OS v9.2.

**Comment by andreas-bulling** [comment]
I can confirm that it also works for me with HomeAssistant OS 9.2

**Comment by jens-maus** [comment]
Ok, I think that we have definitely enough evidence that the issue raised here is solved. So no reason to misuse this ticket system as a discussion or messaging platform.
